mypath: D:\college\学科\大三下课程设计\
my:
  secretkey: sfne
server:
  port: 30001
spring:
  application:
    name: login-service
#  data:
#    redis:
#      host: 120.46.159.231
#      username: default
#      password: 2046
#      database: 59
  data:
    redis:
      host: localhost
#      username: de
#      password: 2046
      database: 0
  mail:
    # 邮件服务器地址
    host: smtp.qq.com
    # 登录用户名
    username: 3182322272@qq.com
    # 密码是邮箱提供商的授权码
    password: pngyglrwwbzddgbj
    # 编码格式
    default-encoding: UTF-8
    port: 587
    properties:
      "mail.smtp.auth": true
      "mail.smtp.starttls.enable": true
      "mail.smtp.starttls.required": true
#      "mail.smtp.socketFactory": javax.net.ssl.SSLSocketFactory
logging:
  level:
    com.music.demo: debug
knife4j:
  basic:
    enable: true
  setting:
    language: zh_cn