mypath: D:\college\学科\大三下课程设计\
spring:
  application:
    name: music-service
logging:
  level:
    com.music.demo: debug
server:
  port: 30000
knife4j:
  basic:
    enable: true
  setting:
    language: zh_cn
